global:
  scrape_interval: 20s  # default 1m 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']  
  
  - job_name: 'linux'
    static_configs:
      - targets: ['localhost:9100']
      
  - job_name: 'batch'
    static_configs:
      - targets: ['localhost:8080']


