{
 "title": "ps-prom-gs",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Batch processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Active Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without(instance) (worker_jobs_active)"
    }
   ]
  },
  {
   "title": "Active Jobs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without(job, os, runtime) (worker_jobs_active)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Jobs Processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(job, os, runtime) (rate(worker_jobs_total{status=\"processed\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(job, os, runtime) (rate(worker_jobs_total{status=\"failed\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(dotnet_total_memory_bytes{job=\"batch\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"batch\"}[5m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  { "title": "Web App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Active Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without(job, os, runtime, method, instance) (http_requests_in_progress)"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(job, os, runtime, method) (http_requests_in_progress)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "90th Percentile Response",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum without(code, job, method, os, runtime) (rate(http_request_duration_seconds_bucket{code=\"200\"}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Slow Mode Delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum without(job, os, runtime) (rate(web_delay_seconds_sum[5m])) / sum without(job, os, runtime) (rate(web_delay_seconds_count[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(dotnet_total_memory_bytes{job=\"web\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"web\"}[5m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Linux Server",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 19 },
   "targets": [
    { "expr": "node_uname_info" }
   ]
  },
  {
   "title": "Batch app",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 19 },
   "targets": [
    {
     "expr": "app_info{job=\"batch\"}"
    }
   ]
  },
  {
   "title": "Web app",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 19 },
   "targets": [
    {
     "expr": "app_info{job=\"web\"}"
    }
   ]
  },
  {
   "title": "Windows Server",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 22 },
   "targets": [
    { "expr": "windows_os_info" }
   ]
  }
 ]
}