global:
  scrape_interval:     15s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']  

  - job_name: 'web'
    file_sd_configs:
      - files:
         - 'web.json'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*'
        action: drop
      - source_labels: [__name__, volume]
        regex: 'windows_logical_disk_free_bytes;(.*)'
        replacement: '${1}'
        target_label: device

  - job_name: 'batch'
    file_sd_configs:
      - files:
         - 'batch.json'
    relabel_configs:
      - source_labels: [runtime]
        regex: container
        target_label: runtime
        replacement: docker
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*'
        action: drop
      - source_labels: [__name__, mountpoint]
        regex: 'node_filesystem_avail_bytes;.*'
        action: replace
        replacement: ""
        target_label: mountpoint
      